FROM ubuntu:bionic

WORKDIR /root

ADD https://deb.frrouting.org/frr/keys.asc ./

RUN apt-get update && apt-get install -y --no-install-suggests --no-install-recommends gpg ca-certificates gpg-agent &&\
    apt-key add keys.asc && rm -rf keys.asc &&\
    echo deb https://deb.frrouting.org/frr bionic frr-stable | tee -a /etc/apt/sources.list.d/frr.list &&\
    sed -i 's:^path-exclude=/usr/share/man:#path-exclude=/usr/share/man:' /etc/dpkg/dpkg.cfg.d/excludes &&\
    apt-get update && env DEBIAN_FRONTEND=noninteractive\
    apt-get install -y --no-install-suggests --no-install-recommends\
    language-pack-es\
    man-db\
    manpages-es\
    manpages-posix\
    apache2\
    bash-completion\
    bind9\
    bridge-utils\
    command-not-found\
    curl\
    dialog\
    dnsutils\
    easy-rsa\
    ebtables\
    ethtool\
    frr-doc\
    frr-pythontools\
    frr-rpki-rtrlib\
    frr-snmp\
    frr\
    ifupdown\
    iperf\
    iptables\
    iputils-arping\
    iputils-clockdiff\
    iputils-ping\
    iputils-tracepath\
    isc-dhcp-client\
    isc-dhcp-common\
    isc-dhcp-relay\
    isc-dhcp-server\
    less\
    lsof\
    lynx\
    mc\
    mtr\
    nano\
    net-tools\
    netcat\
    nginx\
    nmap\
    openvpn\
    python3\
    radvd\
    ssh\
    sudo\
    tcpdump\
    telnet\
    traceroute\
    ufw\
    vim\
    vlan\
    wget\
    whois\
    &&\
    rm -r /usr/lib/locale/* &&\
    echo "es_NI.UTF-8 UTF-8" > /var/lib/locales/supported.d/es &&\
    echo -e "LANG=\"es_NI.UTF-8\"\nLANGUAGE=\"es_NI:es\"" >> /etc/default/locale &&\
    locale-gen --purge &&\
    apt-get remove --autoremove -y hicolor-icon-theme &&\
    rm -rf /var/lib/apt/lists/* /etc/apt/apt.conf.d/docker-clean

ENV LANG es_NI.UTF-8
ENV LANGUAGE es_NI:es
ENV LC_ALL es_NI.UTF-8
ENV PROMPT_COMMAND 'history -a'
ENV TERM xterm-256color
RUN echo "by: Srealmoreno" > .bash_history
RUN sed -i "46s/^/#/"        /etc/skel/.bashrc
RUN sed -i "35,41s/^#//"     /etc/bash.bashrc
RUN sed -i "39b0; 97,99b0; b ;:0 ;s/^#//" .bashrc
RUN for i in arpd ebtables ip ip6tables ip6tables-restore\
    ip6tables-save iptables iptables-apply\
    iptables-save iptables-xml lnstat\
    nstat routef routel rtacct rtmon\
    ss tc vtysh; do\
    package=$(which $i);\
    ln -s $package $(dirname $package)/orig-$(basename $package);\
    done
ADD docker_init /boot/docker_init

RUN echo "\n# Initialize node, this is for gns3.\n# Network interfaces\n# Configuration files\n# Script \$(hosthome).startup\nif [ -f /boot/docker_init ]; then\n\tsource /boot/docker_init\nfi" | tee -a .bashrc /etc/skel/.bashrc

RUN useradd --create-home --shell /bin/bash --groups sudo --uid 1000 anfitrion

CMD [ "bash" ]
